godotengine/godot-blender-exporter

- io_scene_godot/converters/__init__.py
- io_scene_godot/converters/material.py
- io_scene_godot/converters/mesh.py
- io_scene_godot/converters/physics.py
- io_scene_godot/converters/simple_nodes.py
- io_scene_godot/export_godot.py
- io_scene_godot/structures.py
This PR did two things:
1. use NodeTemplate instead of Path to denote a parent in calling **export_node** and **converters/**. Then enables NodeTemplate to keep the children&parent relations. It would be helpful in further developing of animation and armature (it needs to access parent, brother nodes)
2. add a filtering to remove '.' and '/' from node name when creating NodeTemplate. '.' and '/' are legal in Blender but illegal in Godot.
relevant discussion can be found [here](https://github.com/simedis/godot-blender-exporter/pull/1)
> use NodeTemplate instead of Path to keep track of the parent relation while exporting

- LICENSE.txt
This add-on is licensed under GPLv2 or later, as seen in the source code headers.
This closes #7.
> Include a copy of the GPLv2 instead of the GPLv3

- io_scene_godot/converters/mesh.py
- io_scene_godot/structures.py
In the constructor of ```NodePath``` in structure.py. The parameters given to```os.path.relpath()``` have the wrong order. And the only usage of NodePath also passing the parameter in the wrong order. As the third parameters (referer_attr) is designed to be the attribute of the second parameter(referer), it need to be fixed to make the NodePath constructor easy to use.
Also I find the referer, referee are visually confusing, so any suggestion for better naming the parameters ?
> fix wrong order in creating a relative path

- io_scene_godot/export_godot.py
in ```export_node()``` in export_godot.py, the variable returned by the ```exporter()``` function is named as ```parent_gd_node```, however, in that function context, it is the godot node corresponding to the blender object under processing. 
so it is better to be named as ```current_gd_node```, as the exporting of animation data and parented bone would be doing there, this renaming will make it less confusing.
> change a confusing variable name

- io_scene_godot/__init__.py
- io_scene_godot/export_godot.py
- tests/scenes/export_blends.py
Add a check for ARMATURE before exporting parent_bone relation. otherwise, program would crash if configuration has ```export_parent_bone_constraint```set to ```true``` but ```ARMATURE``` not included in ```object_types```.
> fix a crash if ARMATURE not exported while parent_bone relation exported

- io_scene_godot/__init__.py
- io_scene_godot/export_godot.py
The method here should prevent endless loops elsewhere, too. This also includes a ValidationError type for delivering coordinated error messages.
> Fail to find project on Windows

- io_scene_godot/__init__.py
- io_scene_godot/converters/mesh.py
- io_scene_godot/export_godot.py
- io_scene_godot/structures.py
The problem of #36 #37 is that there exists vertex with no bone weights in the mesh. 
As reduz said, 
> the way Godot works (which kind of applies to all modern game engines), unassigned vertices are not really supposed to work
so no-bone-weight vertex brings undefined behavior. I notice there is a [fix in collada exporter](https://github.com/godotengine/collada-exporter/blob/master/io_scene_dae/export_dae.py#L644), I mocked it in this PR, it solve the deform in #36, #37 in rest position, but it is really not robust.  For pose it will still has the mesh deformed, as this fix merely assign the vertex to bone with index 0.
I am thinking about assigning no-bone-weight vertices to their neighboring vertex's bones, but what if their neighboring  vertices also has no bones ? it will be very …
>  solve the deform in rigged mesh brought by no-bone-weight vertex

- io_scene_godot/converters/material.py
- io_scene_godot/export_godot.py
For the past little while, the exporter has only been able to export into directories with a godot.project file somewhere in one of the parent folders. This commit means that if you have the material search path to either "None" or "subfolders" (rather than "project"), then the exporter does not look for the project file.
> Exporting without searching for godot project file

- io_scene_godot/structures.py
On windows, the material search was finding the materials but they weren't showing up in Godot. It turns out this was due to slash direction. Godot always uses linux-style-slashes internally, and so when python used the native OS level slash, godot would fail to find the requested resource.
> Fixes issue with material search materials now showing on windows

- io_scene_godot/converters/material.py
export_settings["path"] does contain the full path including file name, so we need to go one level higher, just like we do when computing imgpath
> Fix searching of materials in export directory

- io_scene_godot/converters/animation.py
- tests/reference_exports/constraint_external_IK.escn
- tests/reference_exports/constraint_internal_IK.escn
fix some bugs brought by #63 
1. fix type bakeup -> backup
2. give name to baked actions (they default have  name 'Action', if multiple action being baked, they will overwrite each other
3. previously, for object has constraint and no active action, constraint will be baked to an action.  currently change to if the object has no animation data `animation_data`, constraint will be baked to an action
> fix export action name

- io_scene_godot/structures.py
Fix issue node path use backslash as sep on windows.
Need to be tested on windows system.
> Fix node path behaviour on windows

- io_scene_godot/converters/animation/constraint_baking.py
As of blender 2.79.6, bake action takes an iterable `frames` argument
isntead of frame_start and frame_end.
Compare
https://docs.blender.org/api/master/bpy_extras.anim_utils.html?highlight=bake_action#bpy_extras.anim_utils.bake_action
to
https://docs.blender.org/api/2.79b/bpy_extras.anim_utils.html?highlight=bake_action#bpy_extras.anim_utils.bake_action
Resolves #131:
```
TypeError: bake_action() missing 1 required keyword-only argument: 'frames'
```
> Use latest bake_action API.

- io_scene_godot/converters/material_node_tree/exporters.py
- io_scene_godot/converters/material_node_tree/node_vistors.py
- io_scene_godot/converters/material_node_tree/shader_functions.py
- io_scene_godot/converters/material_node_tree/shaders.py
- tests/reference_exports/material_cycle/material_anistropy.escn
- tests/reference_exports/material_cycle/material_normal.escn
- tests/reference_exports/material_cycle/material_unpack_texture.escn
1. add comments to provide node information in generated node
2. change `sqrt(roughness)` to `roughness` because blender2.8 changed their shader
3. shorter generated variable name, more readable 
4. fix wrong interpretation of `roughness` of diffuse node, which is Oren Nayar model
> format generated shader code better

- io_scene_godot/converters/animation/constraint_baking.py
Fixes #138.
In blender 2.79, the arguments frame_start and frame_end are
treated as an _inclusive_ range, and the source of bake_action
adds 1 to frame_end.
See
https://developer.blender.org/diffusion/B/browse/blender-v2.79b-release/release/scripts/modules/bpy_extras/anim_utils.py$131
For the same behavior in blender 2.80, we need to increment frame_end
ourselves when constructing the range of frames to pass.
> Correct frame range passed to bake_action.

- io_scene_godot/converters/armature.py
- tests/reference_exports/action_with_constraint/bone_attachment_ik.escn
- tests/reference_exports/armature/armature_bone_attachment.escn
- tests/reference_exports/armature/armature_illegal_bone_name.escn
Instead of exporting BoneAttachments with names like `BoneAttachment`,
`BoneAttachment001`, `BoneAttachment002`, and so on, export them with
names like "${BoneName}BoneAttachment".
This makes your Godot code more robust and readable. If I have
attachments to bones named "Hand.L" and "Hand.R", now in Godot I can
refer to them as "HandLBoneAttachment" and "HandRBoneAttachment"
instead of "BoneAttachment" and "BoneAttachment001".
> Assign useful names to BoneAttachment nodes.

- io_scene_godot/converters/material_node_tree/exporters.py
If a file with the same name exists in the export directory, skip
copying it rather than attempting to copy and throwing the error:
```
shutil.SameFileError: '/tmp/example/texture.png' and
'/tmp/example/texture.png' are the same file
```
This error is common if you share a texture among multiple models.
Fixes #182.
> Skip copying a texture if the file exists.

- io_scene_godot/converters/armature.py
- io_scene_godot/converters/mesh.py
- io_scene_godot/export_godot.py
- Make bone id computing accessible from mesh exporting
- Simplify Armature exporting code
- Store less information in Skeleton node (which is not recommended)
Fix #226
> Refactor armature exporting

- README.md
- io_scene_godot/__init__.py
- io_scene_godot/export_godot.py
Some typos in the descriptions for the Blender GUI were fixed. Also the
names `Godot` and `Blender` were capitalized.
Please note: I didn't touch any of the code that does actual work. So I
probably didn't break anything.
> Fixing some typos.

- io_scene_godot/converters/material/script_shader/node_tree.py
Godot needs image extension name presented in order to recognize it. It
fix the issue on Linux platform when exporting material using image file
without extension name (it is valid on Linux).
> Add file extension name to packed image if needed

- io_scene_godot/converters/material/script_shader/node_converters.py
- io_scene_godot/converters/material/script_shader/node_tree.py
- io_scene_godot/converters/material/script_shader/shader_functions.py
1. Fix crash on RGB and Value const node by adding a new identifier, fix #241 
2. Add support for limited blend type of MixRGB shader node, including
blend type (MIX, ADD, SUB, MUL, DIV, DIFF, DARKEN, LIGHTEN)
> Fix export crash on RGB and Value const node

- io_scene_godot/converters/material/script_shader/node_converters.py
Previously when no texture coordinate input for ImageTexture, always
defaults to Blender Generated Coordinates. However, it is not consistent
with Blender's behaviour, which defaults use UV.
Fix #250 and #260
> Use UV for image texture with no tex coord input

- io_scene_godot/converters/material/script_shader/node_converters.py
Some odd parentheses has snuck into the shader converter code.
> Fix dodgy parentheses

- io_scene_godot/__init__.py
- io_scene_godot/converters/material/material.py
- io_scene_godot/converters/mesh.py
- tests/install_blender.sh
> Add option to export Material as Spatial Material

- io_scene_godot/converters/material/script_shader/shader_functions.py
This pull request improves the number of supported operations in the "Math" node in the shader editor.
* Fixed names of add, power, logarithm and arcsine
* Fixes the number of arguments the trig functions take to 2, since that is how they are called by the other nodes.
* Adds function definitions for the remaining missing math operations:
- sqrt
- absolute
- minimum
- maximum
- less than
- greater than
- round
- floor
- ceil
- fract
- modulo
- arctan2
> Shader math nodes

- io_scene_godot/__init__.py
- io_scene_godot/converters/material/script_shader/shader_functions.py
For the C code we disable the PEP8 check on the long lines.
An alternative would be to wrap before `out float result`, possibly
with a double indentation.
Fixes:
```
io_scene_godot/converters/material/script_shader/shader_functions.py:467:80: E501 line too long (80 > 79 characters)
io_scene_godot/converters/material/script_shader/shader_functions.py:485:80: E501 line too long (81 > 79 characters)
io_scene_godot/converters/material/script_shader/shader_functions.py:491:80: E501 line too long (84 > 79 characters)
io_scene_godot/converters/material/script_shader/shader_functions.py:554:80: E501 line too long (81 > 79 characters)
io_scene_godot/converters/material/script_shader/shader_functions.py:563:80: E501 line too long (82 > 79 characters) …
```
> Fix style issues causing CI failure

- io_scene_godot/converters/utils.py
Flag `calc_loop_triangles` isn't allowed in `mesh.update`: https://docs.blender.org/api/master/bpy.types.Mesh.html#bpy.types.Mesh.update
> Fixes call to mesh.update in Blender 2.81+

- io_scene_godot/converters/simple_nodes.py
Blender 2.80 seems to be using "cutoff_distance" as the attribute for light range instead of "distance".
> Change attribute for light distance for 2.80

- io_scene_godot/converters/material/script_shader/node_converters.py
Tested on `blender2.80` as 2.81 doesn't work yet. But it's relevant to `master` too, so PR'ing here and it should be cherry-picked for 2.80 too.
> Fix invalid substitution in MixRgbNodeConverter

- .travis.yml
- io_scene_godot/converters/mesh.py
Add checks ensuring exported Skeleton Node is not None.
Patch contributed by @Antokolos in #285
> Fix crash on None armature object

- .travis.yml
- io_scene_godot/converters/material/script_shader/node_converters.py
This repo only has reference scenes exported from Blender 2.81.
Therefore, only run smoke test for 2.80 exports and run full
regression tests for 2.81 exports.
> Travis: run regression tests only in 2.81 exporting

- io_scene_godot/converters/utils.py
As long as everything listed in #311 is followed, meshes with shape keys should export correctly 100% of the time now.
> Bugfix for #305

- io_scene_godot/converters/material/script_shader/node_tree.py
I ran into an issue where the texture image of a material didn't exist on disc, which resulted in a crash and nothing exported whatsoever. I guess that's not intended behaviour.
Currently logging a warning if that's the case. Let me know if this violates your coding standards.
> Fix crash for potential non existent texture images.

- requirements.txt
This should fix the "Cannot import name 'SortImports' from 'isort'"
issue caused by isort 5.0
> Update pylint to 2.5.3

- io_scene_godot/export_godot.py
This fixes an issue I'm facing (trying it on blender 2.90.1)
```
Traceback (most recent call last):
File "/home/will/.config/blender/2.90/scripts/addons/io_scene_godot/__init__.py", line 215, in execute
return export_godot.save(self, context, **keywords)
File "/home/will/.config/blender/2.90/scripts/addons/io_scene_godot/export_godot.py", line 318, in save
exp.export()
File "/home/will/.config/blender/2.90/scripts/addons/io_scene_godot/export_godot.py", line 267, in export
self.export_scene()
File "/home/will/.config/blender/2.90/scripts/addons/io_scene_godot/export_godot.py", line 211, in export_scene
self.export_object(obj, root_gd_node)
File "/home/will/.config/blender/2.90/scripts/addons/io_scene_godot/export_godot.py", line 136, in export_object
if (exported_node.parent and …
```
> Check if object has parent instead of checking if parent is None

- README.md
This also mentions glTF 2.0 which is the most full-featured alternative currently available.
> Make the "experimental" signaling more prominent in the README

- requirements.txt
Hi, 
The build is failing due to `isort` in `pylint`. This PR merely pins `pylint` to the latest version.
> update pylint dependency for build

- io_scene_godot/converters/simple_nodes.py
Previously the warning read
"Unknown light type. Use Point, Spot or Sun: Area", which is vague it
looks like Area is part of the supported types.
Fixes #353.
> Clarify warning message for unsupported light.

- Makefile
Since the tests were nested, `make update-examples` no longer worked.
This updates the make rule to handle the nested directories.
> Update `make update-examples` to handle nested directories

- io_scene_godot/converters/physics.py
- tests/reference_exports/action_animation/physics_animation.escn
- tests/reference_exports/armature/armature_with_physics.escn
- tests/reference_exports/mesh/physics.escn
> Set physics properties on a PhysicsMaterial.

- io_scene_godot/converters/utils.py
This makes it easier for the user to figure out which mesh was
troublesome.
> Add mesh name to n-gon warning message.

- io_scene_godot/__init__.py
- io_scene_godot/export_godot.py
If an unexpected error occurred such as key error(for example, an armature modifier's object is None) while exporting, and in next exporting will cause "struct RNA of ExportGodot has been removed" error and will never succeed because different exporter_log_handler is added multiple times but not removed as same times,
If the error 'struct RNA of ExportGodot  has been removed' occurred, the user must reopen Blender to try again,this is very annoying.
So this fix make sure the exporter_log_handler will be correctly removed whenever any error occurred.
> fix 'struct rna of ExportGodot removed' error

- io_scene_godot/__init__.py
- io_scene_godot/converters/utils.py
Based on some simple testing of mine with Blender 3.0, things mostly work with the fixing of a version check that no longer works under the assumption that `2.x` are the only available versions.
Aside from that version check, I updated the `io_scene_godot.export` method (used for testing reference exports) to be able to introspect the exporter properties successfully. This does not actually ensure that the reference exports are working correctly: it simply allows an attempted export to "work".
_**Note:** as mentioned above one of the reference exports throws an error upon being loaded by Blender 3 (does not get to the export step) and many exported scenes differ from the current reference (obviously). So the references would need some attention from someone with experience debugging their …
> Rough update to work with Blender 3.0

- io_scene_godot/converters/animation/animation_data.py
- Blender officially removed `use_inherit_scale`, so it must be fixed to use `inherit_scale`.
- https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API
> Fix use_inherit_scale deprecation, which is removed in 4.0
